# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blowing Stuff
email: rodrigo@blowingstuff.com
description: > # this means to ignore newlines until "baseurl:"
  This is Rodrigo Castro's personal website. Here is where I'll host some of my
  personal projects and blog about some aspects of my life as a web developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blowingstuff.com" # the base hostname & protocol for your site
twitter_username: rodonrails
github_username:  roooodcastro

navbar:
  items:
    - title: Blog
      url: /blog/
    - title: Projects
      url: /projects/
    - title: Whoami
      url: /whoami/

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
exclude: [README.md, bower.json, .gitignore Gemfile Gemfile.lock CNAME]